# Generated by Django 3.0.6 on 2022-01-20 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20220120_0604'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotosDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='API.Photo')),
            ],
        ),
    ]
